## Question-1

In [1]:
import numpy as np

In [2]:
arr=np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


## Question-2

In [3]:
listA = []
n = 5
for i in range(0, n):
    elm = int(input())
    listA.append(elm)
print(listA)
listB = []
m = 5
for i in range(0, n):
    elm = int(input())
    listB.append(elm)
print(listB)
arr=np.array([listA,listB])
arr1=np.concatenate((listA,listB))
print(arr)
print(arr1)
print(np.sort(arr))
print(np.sort(arr1))


5
6
3
6
2
[5, 6, 3, 6, 2]
6
7
3
5
1
[6, 7, 3, 5, 1]
[[5 6 3 6 2]
 [6 7 3 5 1]]
[5 6 3 6 2 6 7 3 5 1]
[[2 3 5 6 6]
 [1 3 5 6 7]]
[1 2 3 3 5 5 6 6 6 7]


## Question-3

In [9]:
arr=np.arange(12).reshape(3,4)
print(arr)
print(arr.shape)
print(arr.size)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
12


## Question-4

In [12]:
import numpy as np
a = np.array([[10],[20],[30]])
b = np.array([[40],[50],[60]])
c = np.dstack((a, b))
print(c)
print(c[np.newaxis, :, :].shape)

[[[10 40]]

 [[20 50]]

 [[30 60]]]
(1, 3, 1, 2)


## Question-5

In [15]:
arr=np.arange(9).reshape(3,3)
arr1=np.arange(10,19).reshape(3,3)
c=np.vstack((arr,arr1))
d=np.hstack((arr,arr1))
print(c)
print(d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 0  1  2 10 11 12]
 [ 3  4  5 13 14 15]
 [ 6  7  8 16 17 18]]


## Question-6

In [20]:
import numpy as np 
  
a = np.array([10, 20, 5, 
              10, 8, 20, 
               8, 9]) 
unique= np.unique(a,return_counts = True) 
print(unique) 
  

(array([ 5,  8,  9, 10, 20]), array([1, 2, 1, 2, 2], dtype=int64))
